master:
  push:
    - stages:
      - name: 发布页面到cdn
        type: cdn:go
        options:
          dist: cases/
          latest: true
          groupAsDomain: false
      wework:
        title: 挂件 ${ORANGE_BRANCH} 分支部署
        notify:
          - alsotang
          - gisonyang