master:
  push:
    - docker:
        image: csighub.tencentyun.com/alsotang/pixui_compile:v4
      stages:
        - name: node 版本
          script: node -v
        - name: 安装 tnpm
          script: npm install @tencent/tnpm -g --registry=http://r.tnpm.oa.com --verbose
        - name: 安装依赖
          script: tnpm i
        - name: pfbs 转换
          script: npm run build
        - name: 发布页面到 cdn
          type: cdn:go
          options:
            dist: dist/cases/
            latest: true
            groupAsDomain: false
      wework:
        title: pixui-benchmark 发布
        notify:
          - alsotang
          - gisonyang